---
options:
  triliovault-ip:
    type: string
    default:
    description: TrilioVault IP Address
  tvault-datamover-ext-usr:
    type: string
    default: nova
    description: nova service user name
  tvault-datamover-ext-group:
    type: string
    default: nova
    description: nova service group name
  tvault-datamover-virtenv:
    type: string
    default: /home/tvault
    description: Trilio Vault home directory
  tvault-datamover-virtenv-path:
    type: string
    default: /home/tvault/.virtenv
    description: Trilio Vault Datamover virtual env
  tv-datamover-conf:
    type: string
    default: /etc/tvault-contego/tvault-contego.conf
    description: Trilio Vault Datamover config file location
  backup-target-type:
    type: string
    default: nfs
    description: |
        Type of backup target.
        Valid types are-
          - nfs
          - s3
  nfs-shares:
    type: string
    default:
    description: NFS Shares mount source path
  nfs-options:
    type: string
    default: nolock,soft,timeo=180,intr,lookupcache=none
    description: NFS Options
  tv-data-dir:
    type: string
    default: /var/triliovault-mounts
    description: TrilioVault data mount point
  tv-data-dir-old:
    type: string
    default: /var/triliovault
    description: Old TrilioVault data dir
  tv-s3-secret-key:
    type: string
    default: sample_s3_secret_key
    description: S3 secret access key
  tv-s3-access-key:
    type: string
    default: sample_s3_access_key
    description: S3 access key
  tv-s3-type:
    type: string
    default: Amazon
    description: |
        S3 type(case sensitive)
          - Amazon
  tv-s3-region-name:
    type: string
    default: sample_s3_region_name
    description: S3 region name
  tv-s3-bucket:
    type: string
    default: sample_s3_bucket_name
    description: S3 bucket name
  tv-s3-endpoint-url:
    type: string
    default: sample_s3_endpoint_url
    description: S3 endpoint URL
  tv-s3-secure:
    type: boolean
    default: false
    description: Use secure connection
