---
- name: Pulling triliovault images
  become: true
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ item.value.image }}"
    auth_username: "{{ triliovault_docker_username }}"
    auth_password: "{{ triliovault_docker_password }}"
    auth_registry: "{{ triliovault_docker_registry }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ triliovault_services }}"
