# This example overlay bundle contains the basic, non-ha charm
# config to deploy Trilio on top of the example cs:openstack-base
# bundle for dev/test purposes.  This is not for production use.
#
# The sample s3 values and ip address(es) must be edited to fit
# the specific model and environment prior to deployment.
#
# ex.
#   juju deploy cs:openstack-base --overlay bundle-trilio-overlay.yaml
#
# tvault config details
trilio-configurator:
  tv-conf-node-ip: 
  tv-conf-user: 
  tv-conf-pass: 
  tv-controller-nodes: 
  tv-virtual-ip: 
  tv-name-server: 
  tv-dom-search-order: 
  tv-timezone: 
  # Openstack config details
  tv-keystone-admin-url: 
  tv-keystone-public-url: 
  tv-dm-endpoint:
  tv-os-username:
  tv-os-password:
  tv-os-tenant-name:
  tv-os-region-name:
  tv-os-domain-id:
  tv-os-trustee-role:
  # Backup details
  tv-backup-target-type:
  tv-s3-type:
  tv-s3-access-key:
  tv-s3-secret-key:
  tv-s3-bucket:
  tv-s3-region-name:
  tv-import-workloads:
