---

- name: copy the Rabbitmq User ssl Cert file
  copy:
    src: "{{rabbitmq_user_ssl_cert}}"
    dest: "/opt/cert/ssl/"
  register: rabbitmq_user_ssl_cert_output
  when: rabbitmq_user_ssl_cert is defined

- name: copy the Rabbitmq User ssl Key file
  copy:
    src: "{{rabbitmq_user_ssl_key}}"
    dest: "/opt/cert/ssl/"
  register: rabbitmq_user_ssl_key_output
  when: rabbitmq_user_ssl_key is defined

- name: copy the Rabbitmq User ssl Ca-Cert file
  copy:
    src: "{{rabbitmq_user_ssl_ca_cert}}"
    dest: "/opt/cert/ssl/"
  register: rabbitmq_user_ssl_ca_cert_output
  when: rabbitmq_user_ssl_ca_cert is defined

- set_fact: rabbitmq_user_ssl_cert_path="{{rabbitmq_user_ssl_cert_output.dest}}"
- set_fact: rabbitmq_user_ssl_key_path="{{rabbitmq_user_ssl_key_output.dest}}"
- set_fact: rabbitmq_user_ssl_ca_cert_path="{{rabbitmq_user_ssl_ca_cert_output.dest}}"

- debug:
    msg: "rabbitmq_user_ssl_cert: {{rabbitmq_user_ssl_cert_path}} rabbitmq_user_ssl_key:{{rabbitmq_user_ssl_key_path}} rabbitmq_user_ssl_ca_cert: {{rabbitmq_user_ssl_ca_cert_path}}"
