---
- name: get python details
  import_tasks: get_python.yml
  tags:
       - datamover-api
       - all-install
       
- name:  install tvault_datamover_api on rhel/centos
  import_tasks: install_rhel.yml
  tags:
       - datamover-api
       - all-install
  when: >
       (ansible_distribution_major_version=="7" and ansible_distribution=="CentOS") or
       (ansible_distribution_major_version=="7" and ansible_distribution=="RedHat")


- name:  install tvault_datamover_api on ubuntu
  import_tasks: install_ubuntu.yml
  tags:
       - datamover-api
       - all-install
  when: ansible_distribution=="Ubuntu"

- name: uninstall tvault_datamover_api
  import_tasks: uninstall.yml
  tags: 
       - datamover-api-uninstall
       - all-uninstall
