---
- name:  install tvault_datamover_api if openstack version is pike/queens
  import_tasks: install_on_queens.yml
  tags:
       - datamover-api
       - all-install

- name: uninstall tvault_datamover_api
  import_tasks: uninstall.yml
  tags: 
       - datamover-api-uninstall
       - all-uninstall
