---

- name: Apply haproxy config for triliovault services
  gather_facts: false
  hosts:
    - haproxy
    - '&enable_haproxy_True'
  serial: '{{ kolla_serial|default("0") }}'
  tags:
    - haproxy   
  tasks:  
    - include_role:
        name: triliovault
        tasks_from: loadbalancer
    when:
      - inventory_hostname in groups['nova-api']
      - enable_haproxy | bool
      - enable_triliovault | bool
      - kolla_action in ['deploy', 'reconfigure', 'upgrade', 'config']

- name: Apply role triliovault
  gather_facts: false
  hosts:
    - nova-api
    - compute
    - enable_triliovault | bool
  serial: '{{ kolla_serial|default("0") }}'
  roles:
    - { role: triliovault,
        tags: triliovault,
        when: enable_triliovault | bool }
