---
- name: find location of manage.py 
  shell: "find {{ ENV_PATH }}  -name '*manage.py' | grep -E 'openstack-dashboard|horizon'"
  register: output

- debug:
    msg: "{{ output.stdout}}"

- name: Collect static files for horizon
  command: "{{ output.stdout}}  collectstatic --noinput"
  verbosity: 3
  notify:
     - restart webserver

- name: compress the collected files
  command: "{{ output.stdout}} compress --force"
  verbosity: 3
  notify:
     - restart webserver
