---

- name: Setup trilio yum repo for queens
  template:
     src: trilio.repo
     dest: "{{trilio_yum_repo_file_path}}"

- name: install tvault horizon plugin packages
  yum:
     update_cache: yes
     name:
        - tvault-horizon-plugin
        - python-workloadmgrclient
     state: present

- name: copy tvault_panel_group.py file to remote location
  copy: src="{{automation_home}}/files/tvault_panel_group.py" dest="{{HORIZON_PATH}}/openstack_dashboard/local/enabled/tvault_panel_group.py" 

- name: copy tvault_admin_panel_group.py file to remote location
  copy: src="{{automation_home}}/files/tvault_admin_panel_group.py" dest="{{HORIZON_PATH}}/openstack_dashboard/local/enabled/tvault_admin_panel_group.py"

- name: copy tvault_panel.py file to remote location
  copy: src="{{automation_home}}/files/tvault_panel.py" dest="{{HORIZON_PATH}}/openstack_dashboard/local/enabled/tvault_panel.py"

- name: copy tvault_settings_panel.py file to remote location
  copy: src="{{automation_home}}/files/tvault_settings_panel.py" dest="{{HORIZON_PATH}}/openstack_dashboard/local/enabled/tvault_settings_panel.py" 

- name: copy tvault_admin_panel.py file to remote location
  copy: src="{{automation_home}}/files/tvault_admin_panel.py" dest="{{HORIZON_PATH}}/openstack_dashboard/local/enabled/tvault_admin_panel.py"

- name: copy tvault_filter.py file to remote location
  copy: src="{{automation_home}}/files/tvault_filter.py" dest="{{HORIZON_PATH}}/openstack_dashboard/templatetags/tvault_filter.py"

- name: restart webserver service 
  service: name={{WebServer}} state=restarted

- name: write content into destination file - sync_static.py 
  copy: src="{{automation_home}}/files/sync_static.py" dest="/tmp/sync_static.py" 
 
- name: Change the working directory to horizon and excute shell command
  shell: ./manage.py shell < /tmp/sync_static.py &> /dev/null
  args:
       chdir: "{{HORIZON_PATH}}"

- name: remove temporary file -  sync_static.py
  file: path=/tmp/sync_static.py state=absent
