---
- name: create apt repo file
  template:
     src: trilio.list
     dest: "{{trilio_apt_repo_file_path}}"

- name: install tvault-horizon-plugin deb packages when using python2
  apt:
     update_cache: yes
     name: "{{ item }}={{ TVAULT_PACKAGE_VERSION }}"
     state: present
     allow_unauthenticated: yes
  with_items:
    - tvault-horizon-plugin
    - python-workloadmgrclient
  notify:
      - restart webserver
  when: PYTHON_VERSION=="python2"
  
- name: install tvault-horizon-plugin deb packages when using python3
  apt:
     update_cache: yes
     name: "{{ item }}={{ TVAULT_PACKAGE_VERSION }}"
     state: present
     allow_unauthenticated: yes
  with_items:
    - tvault-horizon-plugin
    - python-workloadmgrclient
  notify:
      - restart webserver
  when: PYTHON_VERSION=="python3"
