---
- name: create apt repo file
  template:
     src: trilio.list
     dest: "{{trilio_apt_repo_file_path}}"


- name: install tvault-horizon-plugin and python-workloadmgrclient deb packages when using python2
  shell: |
          wget http://{{ IP_ADDRESS }}:{{ PORT_NO }}/deb-repo/deb-repo/python-workloadmgrclient_{{ TVAULT_PACKAGE_VERSION  }}_all.deb
          apt-get install ./python-workloadmgrclient_{{ TVAULT_PACKAGE_VERSION }}_all.deb -y $EXTRA_APT_VAR
          rm -rf python-workloadmgrclient_{{ TVAULT_PACKAGE_VERSION }}_all.deb
          wget http://{{ IP_ADDRESS }}:{{ PORT_NO }}/deb-repo/deb-repo/tvault-horizon-plugin_{{ TVAULT_PACKAGE_VERSION  }}_all.deb
          apt-get install ./tvault-horizon-plugin_{{ TVAULT_PACKAGE_VERSION }}_all.deb -y $EXTRA_APT_VAR
          rm -rf tvault-horizon-plugin_{{ TVAULT_PACKAGE_VERSION }}_all.deb
  when: PYTHON_VERSION=="python2"

- name: install python3-tvault-horizon-plugin and python3-workloadmgrclient deb packages when using python3
  shell: |
          wget http://{{ IP_ADDRESS }}:{{ PORT_NO }}/deb-repo/deb-repo/python3-workloadmgrclient_{{ TVAULT_PACKAGE_VERSION }}_all.deb
          apt-get install ./python3-workloadmgrclient_{{ TVAULT_PACKAGE_VERSION }}_all.deb -y $EXTRA_APT_VAR
          rm -rf python3-workloadmgrclient_{{ TVAULT_PACKAGE_VERSION }}_all.deb
          wget http://{{ IP_ADDRESS }}:{{ PORT_NO }}/deb-repo/deb-repo/python3-tvault-horizon-plugin_{{ TVAULT_PACKAGE_VERSION  }}_all.deb
          apt-get install ./python3-tvault-horizon-plugin_{{ TVAULT_PACKAGE_VERSION }}_all.deb -y $EXTRA_APT_VAR
          rm -rf python3-tvault-horizon-plugin_{{ TVAULT_PACKAGE_VERSION }}_all.deb
  when: PYTHON_VERSION=="python3"
