---
- set_fact:
     automation_home : "{{playbook_dir}}/roles/ansible-horizon-plugin"
  tags: 
    - horizon
    - all-install
    - horizon-uninstall
    - all-uninstall
    
- import_tasks: roles/ansible-datamover-api/tasks/get_python.yml
  tags:
    - horizon
    - all-install
    
- import_tasks: roles/ansible-tvault-contego-extension/tasks/get_venv.yml
  tags:
    - horizon
    - all-install
    
- name: find manage.py file
  import_tasks: find_manage_file.yml
  tags:
    - horizon
    - all-install
    - horizon-uninstall
    - all-uninstall
        
- name: install horizon plugin on controller node
  import_tasks: install_rhel.yml
  tags:
    - horizon
    - all-install
  when: >
       (ansible_distribution_major_version=="7" and ansible_distribution=="CentOS") or
       (ansible_distribution_major_version=="7" and ansible_distribution=="RedHat")

- name: install horizon plugin on controller node
  import_tasks: install_ubuntu.yml
  tags:
    - horizon
    - all-install
  when: ansible_distribution=="Ubuntu"

- name: post install horizon plugin on controller node
  import_tasks: post_install.yml
  tags:
    - horizon
    - all-install

- name: post install collect and compress
  import_tasks: collect_compress.yml
  tags:
    - horizon
    - all-install

- name: uninstall horizon plugin from controller node
  import_tasks: uninstall_rhel.yml
  tags:
    - horizon-uninstall
    - all-uninstall
  when: >
       (ansible_distribution_major_version=="7" and ansible_distribution=="CentOS") or
       (ansible_distribution_major_version=="7" and ansible_distribution=="RedHat")

- name: uninstall horizon plugin from controller node
  import_tasks: uninstall_ubuntu.yml
  tags:
    - horizon-uninstall
    - all-uninstall
  when: ansible_distribution=="Ubuntu"

- name: post uninstall horizon plugin from controller node
  import_tasks: post_uninstall.yml
  tags:
    - horizon-uninstall
    - all-uninstall
    
- name: Remove trilio.pth file after package uninstall
  import_tasks: remove_trilio_pth.yml
  tags:
    - horizon-uninstall
    - all-uninstall
