---
- name: uninstall tvault horizon plugin packages when using python2
  yum:
     update_cache: yes
     name:
        - tvault-horizon-plugin
        - python-workloadmgrclient
     state: absent
  notify:
     - restart webserver
  when: PYTHON_VERSION=="python2"
  
- name: uninstall tvault horizon plugin packages when using python3
  yum:
     update_cache: yes
     name:
        - python3-tvault-horizon-plugin
        - python3-workloadmgrclient
     state: absent
  notify:
     - restart webserver
  when: PYTHON_VERSION=="python3"
