---
- name: ensure that pip of version 7.1.2 is installed on controller
  easy_install: name="http://{{IP_ADDRESS}}:{{PORT_NO}}/packages/pip-{{pip_version}}.tar.gz" state=present
  ignore_errors: yes
 
- name: uninstall python-workloadmanager client 
  pip: name=python-workloadmgrclient state=absent
 
- name: uninstall horizon plugin 
  pip: name=tvault-horizon-plugin state=absent
  notify:
     - restart webserver

- name: ensure that pip of version 7.1.2 is removed from controller
  pip: name=pip  state=absent
