---

- name: find the trilio filter file name and location
  shell: "echo {{NOVA_COMPUTE_FILTERS_FILE}} | sed 's/compute.filters//'"
  register: TRILIOFILTER

- set_fact:
    TRILIO_FILTER : "{{TRILIOFILTER.stdout}}"

- name: create trilio.filters for mount and unmount
  template:
     src: trilio.filters.j2
     dest: "{{TRILIO_FILTER}}trilio.filters"

- name: find location of nova sudoers file
  shell: find /etc/sudoers.d -name "nova*" | grep -Ew  'nova|nova_sudoers'
  register: output

- name: Set file names
  set_fact:
    file_names: "{{ output.stdout.split('\n')}}"
  when: output.stdout != ""

- debug:
    msg: "{{ file_names}}"
    verbosity: "{{ verbosity_level }}"
  when: output.stdout != ""

- name: Add privsep-helper to nova sudoers file
  lineinfile:
     path: "{{ item }}"
     line: "nova ALL = (root) NOPASSWD: /home/tvault/.virtenv/bin/privsep-helper *"
  with_items: "{{file_names}}"
  when: >
    UPDATE_NOVA_SUDOERS_FILE  == "proceed" and
    output.stdout != ""

- name: Added nova sudoers file if not exist
  template: src=nova.j2 dest=/etc/sudoers.d/nova mode=644
  when: output.stdout == ""
