---
- name: create trilio.filters for mount and unmount for RHEL
  template:
     src: trilio.filters.j2
     dest: "{{FILTERS_FILE_PATH_RHEL}}"
  when: ansible_os_family == "RedHat" 

- name: create trilio.filters for mount and unmount for Debian
  template:
     src: trilio.filters.j2
     dest: "{{FILTERS_FILE_PATH_DEBIAN}}"
  when: ansible_os_family == "Debian" 
  
- name: find location of nova sudoers file
  shell: find /etc/sudoers.d -name "nova*" | grep -Ew  'nova|nova_sudoers'
  register: output
  
- debug:
    msg: "{{ output.stdout}}"
    
- name: Add privsep-helper to nova sudoers file for RHEL
  lineinfile:
     path: "{{ output.stdout}}"
     line: "nova ALL = (root) NOPASSWD: /home/tvault/.virtenv/bin/privsep-helper *"
  when: >
    UPDATE_NOVA_SUDOERS_FILE  == "proceed" and
    ansible_os_family == "RedHat"

- name: Add privsep-helper to nova sudoers file For Debian
  lineinfile:
     path: "{{ output.stdout}}"
     line: "nova ALL = (root) NOPASSWD: /home/tvault/.virtenv/bin/privsep-helper *"
  when: >
    UPDATE_NOVA_SUDOERS_FILE  == "proceed" and
    ansible_os_family == "Debian"
