---
- name: create apt repo file
  template:
     src: trilio.list
     dest: "{{trilio_apt_repo_file_path}}"

- name: install tvault-contego virtual env deb package
  apt:
     update_cache: yes
     name: contego={{ TVAULT_CONTEGO_VERSION }}
     state: present
     allow_unauthenticated: yes

- name: install tvault-contego deb package
  apt:
     update_cache: yes
     name: tvault-contego={{ TVAULT_CONTEGO_VERSION }}
     state: latest
     allow_unauthenticated: yes
