---
- name: ensure tvault-object-store service is stopped
  service: name=tvault-object-store  state=stopped enabled=no
  ignore_errors: yes

- name: stop datamover extension service
  service: name=tvault-contego state=stopped enabled=no
  ignore_errors: yes

- name: uninstall tvault contego extension packages when using python2
  yum:
     name:
        - tvault-contego
        - puppet-triliovault
     state: absent
  when: PYTHON_VERSION=="python2"

- name: uninstall tvault contego extension packages when using python3
  yum:
     name:
        - python3-tvault-contego
     state: absent
  when: PYTHON_VERSION=="python3"
