---
- name: uninstall tvault-contego virtual env deb package
  apt:
     name: contego
     state: absent
     allow_unauthenticated: yes
     purge: yes

- name: uninstall tvault-contego deb package
  apt:
     name: tvault-contego
     state: absent
     allow_unauthenticated: yes
     purge: yes
