heat_template_version: 2016-10-14

description: >
  Trilio service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  Debug:
    default: ''
    description: Set to True to enable debugging on all services.
    type: string
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  TrilioVaultClusterVirtualIp:
    default: ''
    description: Provide TrilioVault cluster virtual IP address
    type: string   
  NovaConfFile:
    default: ''
    description: The location of the nova configuration file
    type: string
  NovaDistConfFile:
    default: ''
    description: The location of the default nova distribution configuration file
    type: string
  TrilioVaultVersion:
    default: ''
    description: The location of the default nova distribution configuration file
    type: string
  RedhatOpenstackVersion:
    default: ''
    description: The location of the default nova distribution configuration file
    type: string
  BackupTargetType:
    default: ''
    description: 
    type: string
  NfsShares:
    default: ''
    description: Provide comma separated list of NFS shares to use as backup target
    type: string
  NfsOptions:
    default: ''
    description: NFS mount otpions
    type: string
  SwiftAuthVersion:
    default: ''
    description: Keystone api version for swift authentication
    type: string
  SwiftAuthUrl:
    default: ''
    description: Swift auth url for authentication 
    type: string
  SwiftTenant:
    default: ''
    description: Swift Tenant Name for authentication 
    type: string
  SwiftUsername:
    default: ''
    description: Swift username for authentication 
    type: string
  SwiftPassword:
    default: ''
    description: Swift password for authentication 
    type: string
  SwiftDomainId:
    default: ''
    description: Swift domain id for authentication 
    type: string
  SwiftDomainName:
    default: ''
    description: Swift domain name for authentication 
    type: string
  SwiftRegionName:
    default: ''
    description: Swift region name for authentication 
    type: string
  S3Type:
    default: ''
    description: S3 type like Amazon/Ceph/Minio
    type: string
  S3AccessKey:
    default: ''
    description: S3 access key 
    type: string
  S3SecretKey:
    default: ''
    description: S3 secret key 
    type: string
  S3RegionName: 
    default: ''
    description: S3 region name
    type: string
  S3Bucket:
    default: ''
    description: S3 bucket name
    type: string
  S3EndpointUrl:
    default: ''
    description: S3 endpoint url
    type: string
  S3SslEnabled:
    default: false
    description: S3 ssl enabled
    type: boolean
  S3SignatureVersion:
    default: ''
    description: S3 signature 
    type: string

outputs:
  role_data:
    description: Role data for the trilio role.
    value:
      service_name: tvault-contego
      config_settings:
        trilio::contego::tvault_virtual_ip: {get_param: TrilioVaultClusterVirtualIp}
        trilio::contego::tvault_version: {get_param: TrilioVaultVersion}
        trilio::contego::redhat_openstack_version: {get_param: RedhatOpenstackVersion}
        trilio::contego::nova_conf_file: {get_param: NovaConfFile}
        trilio::contego::nova_dist_conf_file: {get_param: NovaDistConfFile}
        trilio::contego::backup_target_type: {get_param: BackupTargetType}
        trilio::contego::nfs_shares: {get_param: NfsShares}
        trilio::contego::nfs_options: {get_param: NfsOptions}
        trilio::contego::swift_auth_version: {get_param: SwiftAuthVersion}
        trilio::contego::swift_auth_url: {get_param: SwiftAuthUrl}
        trilio::contego::swift_tenant: {get_param: SwiftTenant}
        trilio::contego::swift_username: {get_param: SwiftUsername}
        trilio::contego::swift_password: {get_param: SwiftPassword}
        trilio::contego::swift_domain_id: {get_param: SwiftDomainId}
        trilio::contego::swift_domain_name: {get_param: SwiftDomainName}
        trilio::contego::swift_region_name: {get_param: SwiftRegionName}
        trilio::contego::s3_type: {get_param: S3Type}
        trilio::contego::s3_accesskey: {get_param: S3AccessKey}
        trilio::contego::s3_secretkey: {get_param: S3SecretKey}
        trilio::contego::s3_region_name: {get_param: S3RegionName}
        trilio::contego::s3_bucket: {get_param: S3Bucket}
        trilio::contego::s3_endpoint_url: {get_param: S3EndpointUrl}
        trilio::contego::s3_ssl_enabled: {get_param: S3SslEnabled}
        trilio::contego::s3_signature_version: {get_param: S3SignatureVersion}
      step_config: |
        include ::tripleo::profile::base::trilio::contego
