heat_template_version: queens

description: >
  Trilio Datamover containerized service

parameters:
  DockerTrilioDatamoverImage:
    default: ''
    description: The location of Trilio Datamover container image
    type: string
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  UpgradeRemoveUnusedPackages:
    default: false
    type: boolean
    description: Remove package if the service is being disabled during upgrade
  NovaConfFile:
    default: ''
    description: The location of the nova configuration file
    type: string
  NovaDistConfFile:
    default: ''
    description: The location of the default nova distribution configuration file
    type: string
  RedhatOpenstackVersion:
    default: ''
    description: The location of the default nova distribution configuration file
    type: string
  BackupTargetType:
    default: ''
    description: 
    type: string
  NfsShares:
    default: ''
    description: Provide comma separated list of NFS shares to use as backup target
    type: string
  NfsOptions:
    default: ''
    description: NFS mount otpions
    type: string
  S3Type:
    default: ''
    description: S3 type like Amazon/Ceph/Minio
    type: string
  S3AccessKey:
    default: ''
    description: S3 access key 
    type: string
  S3SecretKey:
    default: ''
    description: S3 secret key 
    type: string
  S3RegionName: 
    default: ''
    description: S3 region name
    type: string
  S3Bucket:
    default: ''
    description: S3 bucket name
    type: string
  S3EndpointUrl:
    default: ''
    description: S3 endpoint url
    type: string
  S3SslEnabled:
    default: false
    description: S3 ssl enabled
    type: boolean
  S3SignatureVersion:
    default: ''
    description: S3 signature 
    type: string

outputs:
  role_data:
    description: Role data for the Trilio Datamover role.
    value:
      service_name: tvault-contego
      config_settings: {}
      puppet_config:
        config_volume: triliodm
        puppet_tags: dmconfig
        step_config: |
            include ::trilio::tripleo::contego           
        config_image: {get_param: DockerTrilioDatamoverImage}
#      kolla_config:
#        /var/lib/kolla/config_files/trilio_dm.json:
#          command: /home/tvault/.virtenv/bin/python /home/tvault/.virtenv/bin/tvault-contego --config-file=/usr/share/nova/nova-dist.conf --config-file=/etc/nova/nova.conf --config-file=/etc/tvault-contego/tvault-contego.conf                   
#          config_files:
#            - source: "/var/lib/kolla/config_files/src/*"
#              dest: "/"
#              merge: true
#              preserve_properties: true
#          permissions:
#            - path: /var/log/nova
#              owner: nova:nova
#              recurse: true     
      docker_config:
        step_5:
          trilio_datamover:
            image: &trilio_datamover_image {get_param: DockerTrilioDatamoverImage}
            net: host
            privileged: true
            user: nova
            restart: always
            volumes:
              list_concat:
                - /var/lib/config-data/puppet-generated/nova_libvirt/etc/nova:/etc/nova:ro
                - /var/run/libvirt/:/var/run/libvirt/
                - /var/lib/config-data/triliodm/etc/tvault-contego:/var/lib/config-data/triliodm/etc/tvault-contego:ro
            command: /home/tvault/.virtenv/bin/python /home/tvault/.virtenv/bin/tvault-contego --config-file=/usr/share/nova/nova-dist.conf --config-file=/etc/nova/nova.conf --config-file=/etc/tvault-contego/tvault-contego.conf
      upgrade_tasks: ''
